### ISSUE TITLE
Support for jdk 8 & 11.

### ISSUE THREAD

**Issue by chisomekweani** [metaloom/qdrant-java-client#10]
@Jotschi I noticed the support for this sdk is currently at jdk 17. Saw the earlier issue about this 
[here](https://github.com/metaloom/qdrant-java-client/issues/8)
and I'd love to offer bandwidth to help with this.

**Comment by Jotschi** [comment]
I still only have the bandwidth and plan to support the current LTS (17). This has nothing to do with the work needed to update the API and the build process. The changes are trivial. I don't want to support 11 and 8 for the future and keep switching to JDK 8 / 11 in my dev environment. Besides I think 8 is dead. Devs should switch to a newer JDK. I don't want to promote and prolong development with JDK 8 / 11.

I hope my reasoning behind this is understandable.

**Comment by andy1xx8** [comment]
@Jotschi JDK 8/11 is the most popular version now there are a lot of systems running using this version. By supporting only JDK 17 u are supporting less than 10% of the whole JVM world

**Comment by Jotschi** [comment]
You are free to create a fork of this project if you really need to use a JVM for which the support was dropped over a year ago. I don't want to invest the continuing effort into this since I have developed it in my private time without any financial backing.
