### ISSUE TITLE
When initializing the QDrantHttpClient, you need to set the OkHttpClient and add some configurations.

### ISSUE THREAD

**Issue by vpday** [metaloom/qdrant-java-client#2]
For instance:
1. Incorporate additional interceptors.
2. Implement other more nuanced configurations.

**Comment by Jotschi** [comment]
Yes, that is a good enhancement. The client builder should incorporate a way to provide an already configured `OkHttpClient` instance.

**Comment by Jotschi** [comment]
Enhancement will be included in next release.

**Comment by Jotschi** [comment]
Enhancement released with v0.12.0
