### ISSUE TITLE
Error while parsing model to JSON.

### ISSUE THREAD

**Issue by vpday** [metaloom/qdrant-java-client#4]
> https://qdrant.github.io/qdrant/redoc/index.html#tag/collections/operation/get_collection

`{
  "result": {
    "config": {
      "params": {
        "vectors": {
          "article": {
            "size": 1536,
            "distance": "Cosine"
          }
        },
      },
      "quantization_config": null
    },
    "payload_schema": {}
  },
  "status": "ok",
  "time": 0.000017681
}
`

1. The CollectionConfig is missing the quantization_config attribute.
2. If there are multiple vectors with inconsistent VectorParams, it might be appropriate to consider using a Map.

**Comment by Jotschi** [comment]
Thanks for reporting. Fixed both issues.

**Comment by Jotschi** [comment]
Fix released with v0.12.0
