### ISSUE TITLE
Error while parsing model to JSON.

### ISSUE THREAD

**Issue by vpday** [metaloom/qdrant-java-client#5]
`{
  "result": [
    {
      "id": 1639887574359322624,
      "version": 0,
      "score": 0.7975686,
      "payload": null,
      "vector": null
    },
    {
      "id": 1639887558504853504,
      "version": 0,
      "score": 0.77643484,
      "payload": null,
      "vector": null
    },
    {
      "id": 1639887521473343488,
      "version": 0,
      "score": 0.7713549,
      "payload": null,
      "vector": null
    }
  ],
  "status": "ok",
  "time": 0.000717863
}
`

An error occurs when calling qDrantHttpClient.searchPoints() function if Snowflake algorithm is used to generate IDs for points.
The error message is: **com.fasterxml.jackson.databind.JsonMappingException: Numeric value (1639887574359322624) out of range of int (-2147483648 - 2147483647).**

**Comment by Jotschi** [comment]
Reproduced

**Comment by Jotschi** [comment]
Fixed. Will be included in next release. Thanks for reporting.

**Comment by Jotschi** [comment]
Fix released with v0.12.0
