### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by cerebox** [metaloom/qdrant-java-client#6]
Hey!
First I want to thank you for this client.
When do you plan to release the next version?
I have been working with the dev branch because I need quantization and it is working very well.
It would be cool to have it published.

**Comment by Jotschi** [comment]
I need to check whether there are any other API changes with the current version of qdrant that need to be added to the client. That takes some time. I'm currently working on something different but I'll check whether I can publish the current changes as is.

**Comment by Jotschi** [comment]
I have released 0.12.0 - Please let me know if you find any issues.
