### ISSUE TITLE
Are there any example for query filters?

### ISSUE THREAD

**Issue by shenyichen** [metaloom/qdrant-java-client#7]
I'm not sure how to pass the filter parameter to searchPoints. Are there any examples that I can refer to? Thanks a lot!

**Comment by Jotschi** [comment]
There are no tests for search but one for delete that uses a filter. Maybe that will help.

https://github.com/metaloom/qdrant-java-client/blob/1cdb65360b64eca25c1e63d9430a96941eb20f30/http/src/test/java/io/metaloom/qdrant/client/http/method/PointHttpClientTest.java#L164
