### ISSUE TITLE
Lack of dependency

### ISSUE THREAD

**Issue by ovidiu-petridean** [metaloom/qdrant-java-client#9]
it does not seem to work due to a lacking dependency.
            PointStruct p1 = PointStruct.of("asd", embeddingsArray)
                    .setPayload("{\"name\": \"first\"}")
                    .setId(1);

cannot access com.fasterxml.jackson.core.JacksonException
[ERROR]   class file for com.fasterxml.jackson.core.JacksonException not found

**Comment by Jotschi** [comment]
jackson-core is a compile dependency. The class is in the dependencies. I assume your project excludes it or you override it with a different jackson dependency. Make sure 2.15.0 is in your project dependencies.
